apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: issuer
spec:
  acme:
    server: "https://acme-v02.api.letsencrypt.org/directory"
    email: "waael@hotmail.co.uk"
    privateKeySecretRef:
      name: issuer
    solvers:
      - dns01:
          route53:
            hostedZoneID: Z0080164COY9BX1JUJ4L
            region: us-east-1 
        selector:
          dnsZones:
          - "cdk-labs.com"
      - http01:
          ingress:
            class: nginx        