name: CDK Diff Workflow
on:
  push:
    paths:
      - 'infra/**'

permissions:
  id-token: write
  contents: read

jobs:
  cdk_synth:
    runs-on: ubuntu-latest

    steps:
    - name: Checking out repository
      uses: actions/checkout@v6

    - name: Running packages for cdk project
      run: npm install

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::648767092427:role/IamRoleForGitHubActionsRunner
        aws-region: us-east-1

    - name: Installing CDK
      run: npm install -g aws-cdk

    - name: Running CDK Synth
      run: cdk synth --all

    - name: Running CDK Synth
      run: cdk diff --all

    - name: Running Checkov scan
      uses: bridgecrewio/checkov-action@v12
      with:
        directory: ./cdk.out
        framework: cloudformation
        output_format: table
        soft_fail: true 