name: CDK Deploy Workflow
on:
  workflow_dispatch:

env:
  AWS_REGION: us-east-1

permissions:
  id-token: write
  contents: read

jobs:
  cdk_deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checking out repository
      uses: actions/checkout@v6

    - name: Setting up node
      uses: actions/setup-node@v6
      with:
        node-version: "25"

    - name: Installing dependencies for cdk project
      run: npm install

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::648767092427:role/IamRoleForGitHubActionsRunner
        aws-region: ${{ env.AWS_REGION }}

    - name: Installing CDK
      run: npm install -g aws-cdk

    - name: Running CDK Deploy
      run: npx cdk deploy --all --require-approval never