name: Docker Workflow
on:
  push:
    paths:
      - "app/**"

env:
  AWS_REGION: us-east-1

permissions:
  id-token: write
  contents: read

jobs:
  docker_image:
    runs-on: ubuntu-latest
    steps:

    - name: checkout repository
      uses: actions/checkout@v6

    - name: building Docker image
      run: docker build -t game-image:v1 .
      working-directory: ./app

    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@0.33.1
      with:
        image-ref: game-image:v1
        format: 'table'
        exit-code: '1'
        vuln-type: 'os,library'
        severity: 'HIGH,CRITICAL'

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ secrets.IAM_ROLE_ARN_GHA_RUNNER }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Authenticating with AWS ECR
      uses: aws-actions/amazon-ecr-login@v2

    - name: Login to Amazon ECR
      uses: aws-actions/amazon-ecr-login@v2
      with:
        mask-password: 'true'

    - name: tagging image with AWS ECR repo
      run: docker tag game-image:v1 ${{ secrets.ECR_REGISTRY_URI }}

    - name: docker image to AWS ECR
      run: docker push ${{ secrets.ECR_REGISTRY_URI }}